# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-20 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0012_shari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shari',
            name='desc',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='shari',
            name='stock',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
