# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-20 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0015_lehgas_choli'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formalshirts',
            old_name='photo',
            new_name='photo1',
        ),
        migrations.AddField(
            model_name='formalshirts',
            name='photo2',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
