# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-21 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0020_sport_kids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tshirt',
            old_name='photo',
            new_name='photo1',
        ),
        migrations.AddField(
            model_name='tshirt',
            name='photo2',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='desc',
            field=models.TextField(max_length=700),
        ),
    ]
